# Generated by Django 3.1.3 on 2021-05-06 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_auto_20210426_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_model',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 17, 2, 5, 296822)),
        ),
        migrations.AlterField(
            model_name='exam_model',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 6, 17, 2, 5, 296822)),
        ),
        migrations.AlterField(
            model_name='question_db',
            name='question',
            field=models.CharField(max_length=300),
        ),
    ]
